name: panel_view_example
description: Example app for the panel_view package.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  panel_view:
    path: ..

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
